// Generates src/lib/icons-data.ts from lucide-static (ISC licence) plus a few brand marks.
// Run: node scripts/build-icons.mjs   (only needed when the icon list below changes)
import { readFileSync, writeFileSync } from 'node:fs';

const LUCIDE = [
  // amenities & rooms
  'wifi', 'car', 'square-parking', 'snowflake', 'fan', 'wind', 'shower-head', 'bath', 'tv', 'concierge-bell',
  'bell-ring', 'shirt', 'coffee', 'cup-soda', 'utensils', 'cooking-pot', 'hand-platter', 'refrigerator',
  'microwave', 'flame', 'thermometer', 'droplets', 'zap', 'plug', 'bed-double', 'bed', 'bed-single', 'sofa',
  'armchair', 'lamp', 'lamp-desk', 'door-open', 'key-round', 'luggage', 'baby', 'cigarette-off', 'accessibility',
  'sparkles', 'sparkle', 'cctv', 'fire-extinguisher', 'shield-check', 'shield', 'lock', 'id-card', 'user-check',
  'stethoscope', 'pill', 'hospital', 'dumbbell', 'gamepad-2', 'film', 'music', 'book-open', 'briefcase-business',
  'party-popper', 'heart-handshake', 'heart', 'thumbs-up', 'award', 'badge-percent', 'tag', 'wallet',
  'credit-card', 'shopping-bag', 'store', 'fuel', 'wrench', 'sun', 'moon', 'trees', 'mountain', 'landmark',
  'building', 'hotel', 'house', 'church', 'bus', 'train-front', 'plane', 'navigation', 'map', 'map-pin',
  'clock', 'calendar-days', 'users', 'user', 'star', 'phone', 'mail', 'message-circle', 'quote', 'camera',
  'images', 'image', 'layout-grid',
  // interface
  'check', 'circle-check', 'x', 'menu', 'search', 'chevron-down', 'chevron-up', 'chevron-left', 'chevron-right',
  'arrow-right', 'arrow-left', 'arrow-up', 'arrow-down', 'external-link', 'plus', 'minus', 'trash', 'pencil',
  'copy', 'eye', 'eye-off', 'upload', 'download', 'log-out', 'settings', 'palette', 'type', 'file-text',
  'files', 'newspaper', 'inbox', 'gauge', 'shield-alert', 'rotate-ccw-clock', 'database', 'cookie', 'globe', 'link',
  'megaphone', 'list', 'circle-question-mark', 'info', 'triangle-alert', 'grip-vertical', 'funnel', 'share-2',
  'smartphone', 'key', 'monitor', 'panel-left', 'rotate-ccw', 'sliders-horizontal', 'refresh-cw'
];

const BRANDS = {
  whatsapp:
    '<path fill="currentColor" stroke="none" d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 0 1 2.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413Z"/>',
  instagram:
    '<rect width="20" height="20" x="2" y="2" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/>',
  facebook: '<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>',
  youtube:
    '<path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17"/><path d="m10 15 5-3-5-3z"/>',
  google:
    '<path fill="currentColor" stroke="none" d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"/>',
  x: '<path fill="currentColor" stroke="none" d="M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.638 7.584H.474l8.6-9.83L0 1.154h7.594l5.243 6.932ZM17.61 20.644h2.039L6.486 3.24H4.298Z"/>',
};

const out = {};
for (const name of [...new Set(LUCIDE)]) {
  let src;
  try {
    src = readFileSync(`node_modules/lucide-static/dist/esm/icons/${name}.mjs`, 'utf8');
  } catch {
    console.warn('skipping missing icon', name);
    continue;
  }
  const svg = src.match(/`([\s\S]*?)`/)[1];
  const inner = svg
    .replace(/^[\s\S]*?<svg[\s\S]*?>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s*\n\s*/g, '')
    .replace(/\s*\/>/g, '/>');
  out[name] = inner;
}
Object.assign(out, BRANDS);

const body =
  '// Generated by scripts/build-icons.mjs — do not edit by hand.\n' +
  '// Icons: Lucide (ISC licence, https://lucide.dev); brand marks: Simple Icons (CC0) / Lucide legacy.\n' +
  `export const ICONS: Record<string, string> = ${JSON.stringify(out, null, 1)};\n`;
writeFileSync('src/lib/icons-data.ts', body);
console.log(`wrote ${Object.keys(out).length} icons`);
